### ISSUE TITLE
mount_sshfs error

### ISSUE THREAD

**Issue by royfrancis** [UPPMAX/uppmax_in_a_can#1]
Installation of the singularity container and creation of the sif file has gone smoothly. I get an error at `./mount_sshfs.sh ` step.

```
$ ./mount_sshfs.sh         
UPPMAX username:
<user>
UPPMAX password:
fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf
```

Ubuntu 18.04 running zsh.

**Comment by dahlo** [comment]
Yes, you will have to uncomment that line in /etc/fuse.conf

It's part of the documentation now.
